[General]
bypass-system-proxy = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local
dns-server = system, 119.29.29.29, 223.5.5.5, 1.1.1.1

[Proxy]
TikTok-Socks5 = socks5, 1.2.3.4, 1080, username=your_user, password=your_pass

[Rule]
RULE-SET,https://raw.githubusercontent.com/AIX-Open/shadowrocket-rules-mirror/main/Shadowrocket/TikTok/TikTok.list,TikTok-Socks5

GEOIP,CN,DIRECT
FINAL,DIRECT
